"""
Clara Pipeline - Task Tracker
Creates a task entry per account in a local JSON task board.
Free alternative to Asana — no account or API needed.
"""

import json
import os
from datetime import datetime
from pathlib import Path

TASKS_FILE = Path(__file__).parent.parent / "outputs" / "task_board.json"


def load_tasks() -> dict:
    if TASKS_FILE.exists():
        with open(TASKS_FILE) as f:
            return json.load(f)
    return {"tasks": [], "last_updated": None}


def save_tasks(board: dict):
    TASKS_FILE.parent.mkdir(parents=True, exist_ok=True)
    board["last_updated"] = datetime.now().isoformat()
    with open(TASKS_FILE, "w") as f:
        json.dump(board, f, indent=2)


def create_task(account_id: str, company_name: str, stage: str,
                unknowns: list = None) -> dict:
    """
    Create or update a task for an account.
    stage: 'demo_processed' or 'onboarding_complete'
    """
    board = load_tasks()

    # Check if task already exists for this account
    existing = next((t for t in board["tasks"] if t["account_id"] == account_id), None)

    status_map = {
        "demo_processed":      "In Progress — Awaiting Onboarding",
        "onboarding_complete": "Complete — Ready for Retell Import"
    }

    if existing:
        # Update existing task
        existing["stage"] = stage
        existing["status"] = status_map.get(stage, stage)
        existing["updated_at"] = datetime.now().isoformat()
        if stage == "onboarding_complete":
            existing["v2_generated"] = True
        if unknowns:
            existing["open_questions"] = unknowns
        task = existing
    else:
        # Create new task
        task = {
            "task_id": f"CLARA-{account_id}",
            "account_id": account_id,
            "company_name": company_name,
            "stage": stage,
            "status": status_map.get(stage, stage),
            "v1_generated": True,
            "v2_generated": stage == "onboarding_complete",
            "open_questions": unknowns or [],
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
            "retell_import_status": "pending_manual_import",
            "notes": f"Auto-generated by Clara Pipeline"
        }
        board["tasks"].append(task)

    save_tasks(board)
    return task


def print_board():
    """Print a summary of all tasks."""
    board = load_tasks()
    tasks = board.get("tasks", [])
    print(f"\n{'='*60}")
    print(f"  📋 CLARA TASK BOARD — {len(tasks)} accounts")
    print(f"{'='*60}")
    for t in tasks:
        questions = len(t.get("open_questions", []))
        print(f"\n  [{t['task_id']}] {t['company_name']}")
        print(f"    Status:  {t['status']}")
        print(f"    v1: ✅  v2: {'✅' if t['v2_generated'] else '⏳'}")
        if questions:
            print(f"    ❓ {questions} open question(s)")
    print(f"\n{'='*60}\n")


if __name__ == "__main__":
    print_board()
